### ISSUE TITLE
Provisioning Profiles

### ISSUE THREAD

**Issue by joaorsfonseca** [microsoftgraph/msgraph-training-xamarin#11]
Hi.
While running this sample on iPhone simulator i am facing this error:
**Could not find any available provisioning profiles for GraphTutorial.iOS on iOS.**

What am I missing? Also on the simulator.

Thanks.

**Comment by jasonjoh** [comment]
That's an issue with your Apple developer account. You need to link it with Visual Studio. This might help: https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/manual-provisioning?tabs=windows
