### ISSUE TITLE
Demo solutions don't build with latest VS

### ISSUE THREAD

**Issue by kzu** [microsoftgraph/msgraph-training-xamarin#15]
Downloaded latest version of the repo. 
Open in VS latest public preview.
Build results in:

![image](https://user-images.githubusercontent.com/169707/72008928-9e5f7b80-3233-11ea-93ee-002c847000f1.png)

With no pending nuget restores or anything. Added binlog from running `msbuild -bl -r` for the main netstandard lib project 

[msbuild.zip](https://github.com/microsoftgraph/msgraph-training-xamarin/files/4036900/msbuild.zip)

**Comment by jasonjoh** [comment]
Did you complete this step?

https://github.com/microsoftgraph/msgraph-training-xamarin/tree/master/demos/03-add-msgraph#configure-the-sample

**Comment by GolfMan2000** [comment]
The sample has the OAuth... file as .example extension.  Create a class with the name of OAuth... And then replace its content with the one with the extension .example...

It seems to compile but I can't seem to deploy it????

**Comment by kzu** [comment]
Did that step, it builds now. I wonder why have such a weird approach to a sample. It should build off the bat, then have users change a constant here and there.

**Comment by jasonjoh** [comment]
It's to prevent accidentally checking in your app ID. Glad you got it running.

**Comment by GolfMan2000** [comment]
I think the point is well made by @Kzu  & @jasonjoh. One need to protect the credential. However a tutorial has to be such that a dummy credential is used in sample OR ReadMe file has to explicitly say that the file has the .example extension and explain how to deal with it. Sometime what is hard for people to understand that when you are in early stages of learning something, its very hard to think outside of what is explicitly given to you.

To this day while I can compile the sample I can't deploy it to Android7.0. I have posted about it. This should be up and running right out of the gate.

Microsoft should have someone in the staff go though these tutorial each time a change is made. Their lack of such testing causes frustrations and lots of back and forth session such as this thread.

**Comment by jasonjoh** [comment]
Thanks @GolfMan2000. There is a README, the one I linked above. We also do test this when we change it, but we do not validate it back to older versions of Android.

**Comment by GolfMan2000** [comment]
Is there any graph tutorial available that will deploy to Android 7.0
