### ISSUE TITLE
UWP crash 

### ISSUE THREAD

**Issue by jupagose** [microsoftgraph/msgraph-training-xamarin#16]
**Microsoft.Identity.Client.MsalClientException: 'User canceled authentication.'** Happens just trying to signin. 

Happens at 

        private async void OnSignIn(object sender, EventArgs e)
        {
            await (Application.Current as App).SignIn();
        }

**Comment by jasonjoh** [comment]
Thanks @jupagose. I believe this is fixed in the new version in the refresh-tutorial branch, which I'll be merging later this week. Can you give that code a try?

https://github.com/microsoftgraph/msgraph-training-xamarin/tree/refresh-tutorial/demo
