### ISSUE TITLE
Function definition missing - GetUtcStartOfWeekInTimeZone 

### ISSUE THREAD

**Issue by sinhakislay** [microsoftgraph/msgraph-training-xamarin#22]
**Where did you get the code?**

- [ x] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

**Describe the bug**
A function definition is missing

**To Reproduce**
1. Follow the tutorial till here https://docs.microsoft.com/en-us/graph/tutorials/xamarin?tutorial-step=4
2. In this steps CalendarPage-xaml and .cs file has been explained
3. You have refer to a function GetUtcStartOfWeekInTimeZone in the .cs file
4. But this method is not defined in the tutorial hence a build error will occur

**Expected behavior**
There should not be a build error

**Desktop (please complete the following information):**
 - OS: Windows Andriod emulator

**Dependency versions**
 - Authentication library (MSAL, etc.) version:
 - Graph library (Graph SDK, REST library, etc.) version:  

**Additional context**
to solve the problem I used below function definition but for this the line var startOfWeek = GetUtcStartOfWeekInTimeZone(DateTime.Today, App.UserTimeZone); needs to be changed to var startOfWeek = GetUtcStartOfWeekInTimeZone(DateTime.Today, App.UserTimeZone.ToString()); in CalendarPage.xaml.cs file

```
        private static DateTime GetUtcStartOfWeekInTimeZone(DateTime today, string timeZoneId)
        {
            // Time zone returned by Graph could be Windows or IANA style
            // .NET Core's FindSystemTimeZoneById needs IANA on Linux/MacOS,
            // and needs Windows style on Windows.
            // TimeZoneConverter can handle this for us
            TimeZoneInfo userTimeZone = TZConvert.GetTimeZoneInfo(timeZoneId);

            // Assumes Sunday as first day of week
            int diff = System.DayOfWeek.Sunday - today.DayOfWeek;

            // create date as unspecified kind
            var unspecifiedStart = DateTime.SpecifyKind(today.AddDays(diff), DateTimeKind.Unspecified);

            // convert to UTC
            return TimeZoneInfo.ConvertTimeToUtc(unspecifiedStart, userTimeZone);
        }

**Comment by jasonjoh** [comment]
Thank you for reporting, you're right this was omitted from the instructions. I'll get it fixed.

**Comment by jasonjoh** [comment]
The missing function is here: https://github.com/microsoftgraph/msgraph-training-xamarin/blob/6b9dcc03f48cf7eeb4bfcb1fe6e9f65d9ea064f8/demo/GraphTutorial/GraphTutorial/CalendarPage.xaml.cs#L63-L73
