### ISSUE TITLE
Creating WebHooks/Notifications using VisualStudio

### ISSUE THREAD

**Issue by GolfMan2000** [microsoftgraph/msgraph-training-xamarin#28]
Per @KyleWang-MSFT in a thread

https://docs.microsoft.com/en-us/answers/questions/461499/get-notification-of-folder-change-in-personal-oned.html?childToView=494081#comment-494081

Can someone help?

**Comment by jasonjoh** [comment]
@GolfMan2000 unfortunately we're not able to provide developer support in our GitHub sample repositories. As mentioned in that thread, there is a [Learn module](https://docs.microsoft.com/learn/modules/msgraph-changenotifications-trackchanges) for working with change notifications. We also have a [.NET sample](https://github.com/microsoftgraph/aspnetcore-webhooks-sample). Note that Graph sends change notifications via a webhook, which means you have to have some sort of web endpoint protected with SSL for Graph to send the notification too. I'm not sure this is possible in Xamarin.

**Comment by GolfMan2000** [comment]
I posted your response back on the thread

Get Notification of folder change in Personal OneDrive using Xamarin CrossPlatform & Graph - Microsoft Q&A<https://docs.microsoft.com/en-us/answers/questions/461499/get-notification-of-folder-change-in-personal-oned.html#comment-494081>

Thank you!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by GolfMan2000** [comment]
Good morning

Tried your recommendation of .NET sample<https://github.com/microsoftgraph/aspnetcore-webhooks-sample> which is crashing. I like to understand if I am on right path.

The tutorial is for desktop but can I run it on Android Mobile? Would Ngrok will support Mobile.

My objective is to have Onedrive notify my Graph Mobile App that user has deleted a file in a particular DriveItem.

If there is no such solution available then perhaps the user can send an email to my app but is there a Mobile Android sample available for receiving/reading an email…many samples are for sending email.

Thank you

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jasonjoh** [comment]
Posted on Q&A.
