### ISSUE TITLE
MPN ID required for App Registration (is it possible to add chapter about setting up "Accounts in this organizational directory only (<tenant> only - Single tenant)")

### ISSUE THREAD

**Issue by ncikac** [microsoftgraph/msgraph-training-xamarin#33]
This example is great. However it shows scenario where user accessing API is "Accounts in any organizational directory (Any Azure AD directory - **Multitenant**)". To do App registration - it would require MPN ID - basically developer has to be MS Partner company employee. Is it possible to explain how to do App registration for scenario where user accessing APIS is "Accounts in this organizational directory only (<tenant> only - **Single** tenant)" ?
Thank you. Nikola

**Comment by jasonjoh** [comment]
@ncikac I'm not sure what you mean by requiring an MPN ID to register your app. Creating a multi-tenant app registration doesn't require this to my knowledge. However, to answer your question about making it a single-tenant app, it only requires a couple of changes.

- Register the app choosing the single-tenant option
- Add your tenant ID to the `PublicClientApplication` using the `WithTenantId` method. So this:
  https://github.com/microsoftgraph/msgraph-training-xamarin/blob/40aa0edb16f694329477c78a44233fa590542ae4/demo/GraphTutorial/GraphTutorial/App.xaml.cs#L101-L103

  Becomes:
  ```csharp
  var builder = PublicClientApplicationBuilder
      .Create(OAuthSettings.ApplicationId)
      .WithTenantId("YOUR TENANT ID")
      .WithRedirectUri(OAuthSettings.RedirectUri);
  ```

**Comment by ncikac** [comment]
Hi Jason,

thank you for fast response.

Do I keep Redirect URI filed in AAD reg. form empty, or it should be set to some value? RedirectUri const in OAuthSettings.cs is still referenced.

***@***.***

Regards,

Nikola

**Comment by jasonjoh** [comment]
You still need a redirect, the one the sample uses should be fine, but you can customize it to use your own domain name.

**Comment by ncikac** [comment]
Hi Jason,

it works now👍 Excellent. Really thank you for fast response.

Regarding this MPN ID.
This is the warning that I receive.

***@***.***

Regards,

Nikola

**Comment by jasonjoh** [comment]
Glad it's working for you. Happy coding!
