### ISSUE TITLE
Update for MSAL 3.x

### ISSUE THREAD

**Issue by sebfrie** [microsoftgraph/msgraph-training-xamarin#5]
Unfortunately, this sample is outdated and cannot be easily built after upgrading the referenced nuget packages. Are there any plans on updating this to the new version?

**Comment by jasonjoh** [comment]
MSAL 3.x introduces breaking changes, so for this sample as-is you need to stay at 2.7.x. It is in our backlog to update this to 3.x.

**Comment by sebfrie** [comment]
Thanks for the clarification. Any timeline to share?

**Comment by jasonjoh** [comment]
Nothing concrete. I'd like to get all of our "training" samples updated to 3.x soon though, so hopefully in the next 2-3 weeks.

**Comment by jasonjoh** [comment]
@sebfrie I'm investigating this now and considering upgrading the project to a clean project created with VS 2019. What version of Visual Studio are you using?

**Comment by sebfrie** [comment]
I'm using VS 2019 (updated today to 16.1.0). I really appreciate your work and am looking forward to the updated tutorial.

**Comment by jasonjoh** [comment]
Let me know if you have any trouble with this updated version. Happy coding!
